# Generated by Django 4.0.4 on 2022-05-10 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historicalreview_historicalportfolio_historicalasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreview',
            name='overall_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Recommend significant changes'), (2, 'Recommend moderate changes'), (3, 'Recommend minor changes'), (4, 'Recommend little to no change'), (5, 'Recommend no change')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='historicalreview',
            name='risk_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Recommend significant changes'), (2, 'Recommend moderate changes'), (3, 'Recommend minor changes'), (4, 'Recommend little to no change'), (5, 'Recommend no change')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='overall_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Recommend significant changes'), (2, 'Recommend moderate changes'), (3, 'Recommend minor changes'), (4, 'Recommend little to no change'), (5, 'Recommend no change')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='risk_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Recommend significant changes'), (2, 'Recommend moderate changes'), (3, 'Recommend minor changes'), (4, 'Recommend little to no change'), (5, 'Recommend no change')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='description',
            field=models.TextField(verbose_name='Suggestions and/or feedback'),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(verbose_name='Suggestions and/or feedback'),
        ),
    ]
