# Generated by Django 4.0.4 on 2022-05-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_historicalportfolio_risk_tolerance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalportfolio',
            name='time_horizon',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='time_horizon',
        ),
    ]
