# Generated by Django 4.0.4 on 2022-05-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_historicalportfolio_time_horizon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='holdings',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='holdings',
            field=models.FloatField(),
        ),
    ]
