# Generated by Django 4.0.4 on 2022-05-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_customuser_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='display_name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='username'),
        ),
    ]
