# Generated by Django 4.0.4 on 2022-05-12 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='display_name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255, verbose_name='username'),
            preserve_default=False,
        ),
    ]
