# Generated by Django 4.0.4 on 2022-05-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Show on leaderboard'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Show on leaderboard'),
        ),
    ]
